[build]
    publish="dist"

[[redirects]]
from = "/"
to = "/fr/index.html"
status = 200
force = false
conditions = {Language = "fr"}

[[redirects]]
from = "/"
to = "/en/index.html"
status = 200
force = false
conditions = {Language = "en"}

[[redirects]]
from = "/"
to = "/fr/index.html"
status = 200
force = false

[[redirects]]
from = "/*"
to = "/fr/404.html"
status = 404
force = false
conditions = {Language = "fr"}

[[redirects]]
from = "/*"
to = "/en/404.html"
status = 404
force = false
conditions = {Language = "en"}
